//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Google.Analytics.Domain.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlRecources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlRecources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Google.Analytics.Domain.Sql.SqlRecources", typeof(SqlRecources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into BUFFER_DIC_CLIENT (
        ///	client_id,
        ///	regions,
        ///	browser,
        ///	create_date)
        ///	values (
        ///	@client_id,
        ///	@regions,
        ///	@browser,
        ///	getdate()).
        /// </summary>
        internal static string InsertBufferDicClient {
            get {
                return ResourceManager.GetString("InsertBufferDicClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into DWH_BUFFER_BILLING.dbo.BUFFER_FCT_BILLING
        ///		(client_id,
        ///			utm_source,
        ///			utm_medium,
        ///			utm_campaign,
        ///			quality_id,
        ///			is_liquid,
        ///			sf_status_id,
        ///			register_date,
        ///			sf_load_date,
        ///			pay_date,
        ///			register_step_id,
        ///			region_name,
        ///			tariff_name,
        ///			tariff_payment,
        ///			payment_summ,
        ///			promocode,
        ///			trial_card,
        ///			utm_term,
        ///			create_date,
        ///			payment_history_id,
        ///			login)
        ///	values
        ///		(@GoogleAnalyticId,
        ///			@UtmSource,
        ///			@UtmMedium,
        ///			@UtmCampaign,
        ///			@QualityGroup,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertBufferFctBilling {
            get {
                return ResourceManager.GetString("InsertBufferFctBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into BUFFER_FCT_SESSION (
        ///	session_id,
        ///	client_id,
        ///	session_time,
        ///	create_date,
        ///	is_reg)
        ///	values (
        ///	@session_id,
        ///	@client_id,
        ///	@session_time,
        ///	getdate(),
        ///	@is_reg).
        /// </summary>
        internal static string InsertBufferFctSession {
            get {
                return ResourceManager.GetString("InsertBufferFctSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into BUFFER_FCT_SESSION_CHANNEL (
        ///	session_id,
        ///	utm_source,
        ///	utm_medium,
        ///	utm_campaign,
        ///	utm_term,
        ///	utm_placement,
        ///	create_date)
        ///	values (
        ///	@session_id,
        ///	@utm_source,
        ///	@utm_medium,
        ///	@utm_campaign,
        ///	@utm_term,
        ///	null,
        ///	getdate()).
        /// </summary>
        internal static string InsertBufferFctSessionChannel {
            get {
                return ResourceManager.GetString("InsertBufferFctSessionChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into BUFFER_FCT_SESSION_HITS (
        ///	session_id,
        ///	page_in_url,
        ///	page_out_url,
        ///	hit_id,
        ///	create_date)
        ///	values(
        ///	@session_id,
        ///	@page_in_url,
        ///	@page_out_url,
        ///	@hit_id,
        ///	getdate()).
        /// </summary>
        internal static string InsertBufferFctSessionHits {
            get {
                return ResourceManager.GetString("InsertBufferFctSessionHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_account_reg_date
        ///		(dimension2,
        ///			dimension5,
        ///			[sessions],
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@AccountRegDate,
        ///			@Sessions,
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithAccountRegDate {
            get {
                return ResourceManager.GetString("InsertReportWithAccountRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_company_id
        ///		(dimension2,
        ///			dimension4,
        ///			[sessions],
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@CompanyId,
        ///			@Sessions,
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithCompanyId {
            get {
                return ResourceManager.GetString("InsertReportWithCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_conversions
        ///		(dimension2,
        ///			[sessions],
        ///			sessionDuration,
        ///			goal1Completions,
        ///			goal2Completions,
        ///			goal3Completions,
        ///			pageviewsPerSession,
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@Sessions,
        ///			@SessionDuration,
        ///			@Goal1Completions,
        ///			@Goal2Completions,
        ///			@Goal3Completions,
        ///			@PageviewsPerSession,
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithConversions {
            get {
                return ResourceManager.GetString("InsertReportWithConversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_employees
        ///		(dimension2,
        ///			dimension9,
        ///			[sessions],
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@Employyes,
        ///			@Sessions,
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithEmployees {
            get {
                return ResourceManager.GetString("InsertReportWithEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_page
        ///		(dimension2,
        ///			dimension11,
        ///			dimension12,
        ///			[date],
        ///			[sessions],
        ///			hits,
        ///			sessionDuration,
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@NumberViewPage,
        ///			@PageUrl,
        ///			@Date,
        ///			@Sessions,
        ///			@Hits,
        ///			@SessionDuration,		
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithPages {
            get {
                return ResourceManager.GetString("InsertReportWithPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_payment_date
        ///		(dimension2,
        ///			dimension10,
        ///			[sessions],
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@PaymentDate,
        ///			@Sessions,
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithPaymentDate {
            get {
                return ResourceManager.GetString("InsertReportWithPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_product
        ///		(dimension2,
        ///			dimension7,
        ///			[sessions],
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@Product,
        ///			@Sessions,
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithProduct {
            get {
                return ResourceManager.GetString("InsertReportWithProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_session_type
        ///		(dimension2,
        ///			dimension6,
        ///			[sessions],
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@SessionType,
        ///			@Sessions,
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithSessionType {
            get {
                return ResourceManager.GetString("InsertReportWithSessionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_tariff_id
        ///		(dimension2,
        ///			dimension8,
        ///			[sessions],
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@TariffId,
        ///			@Sessions,
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithTariff {
            get {
                return ResourceManager.GetString("InsertReportWithTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_user_id
        ///		(dimension2,
        ///			dimension3,
        ///			[sessions],
        ///			create_date)
        ///	values
        ///		(@SessionId,
        ///			@UserId,
        ///			@Sessions,
        ///			getdate());.
        /// </summary>
        internal static string InsertReportWithUserId {
            get {
                return ResourceManager.GetString("InsertReportWithUserId", resourceCulture);
            }
        }
    }
}
